name: 🚀 Deploy bot on push

on:
  push:
    branches:
      - main # Adjust this to your target branch

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3
      
      - name: Sync files via SFTP
        uses: appleboy/scp-action@master # Use the latest stable version
        with:
          host: ${{ secrets.SFTP_SERVER }}      # Your SFTP server address
          username: ${{ secrets.SFTP_USERNAME }}  # Your SFTP username
          password: ${{ secrets.SFTP_PASSWORD }}  # Your SFTP password
          port: 22                                 # SFTP port, typically 22
          source: "./**"                           # Local files to upload
          target: "/path/to/your/remote/dir/"     # Remote directory where files should be uploaded
          strip_components: 1                      # Optional: Strip the first component of the path
